# Generated by Django 5.2.8 on 2025-11-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emid", models.IntegerField()),
                ("ename", models.CharField(max_length=30)),
                ("desg", models.CharField(max_length=50)),
                ("loc", models.CharField(max_length=30)),
                ("salary", models.IntegerField(max_length=30)),
                ("exp", models.IntegerField(max_length=30)),
                ("status", models.IntegerField()),
            ],
        ),
    ]
