# Generated by Django 5.2.8 on 2025-11-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="exp",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="registration",
            name="salary",
            field=models.IntegerField(),
        ),
    ]
