# Generated by Django 5.2.8 on 2025-11-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cname", models.CharField(max_length=50)),
                ("cadd", models.CharField(max_length=90)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("unm", models.CharField(max_length=70)),
                ("pw", models.CharField(max_length=70)),
            ],
        ),
    ]
