# Generated by Django 5.2.8 on 2025-11-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villaAgency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='mobilenumber',
            field=models.CharField(max_length=15),
        ),
    ]
